CREATE OR REPLACE TRIGGER TRG_CUSTOMER 
BEFORE INSERT OR UPDATE ON CUSTOMER 
FOR EACH ROW 
DECLARE TESTVAR VARCHAR2(20) := '@';
BEGIN

    IF (:NEW.CREDITS < 0) THEN 
        RAISE_APPLICATION_ERROR (-20999,'THE VALUE IS TO LOW');
    END IF;
    
    IF (:NEW.BIRTHDAY >= SYSDATE) THEN 
        RAISE_APPLICATION_ERROR (-20998,'THE BIRTHDAY IS TO YOUNG');
    END IF;
    
    IF (UPDATING) THEN 
    
      IF(:OLD.BIRTHDAY <> :NEW.BIRTHDAY) THEN 
          RAISE_APPLICATION_ERROR (-20997, 'CANT CHANGE THE DATE');
      END IF;
      
      IF REGEXP_LIKE(TESTVAR, '/@') THEN
          DBMS_OUTPUT.PUT_LINE(TESTVAR || 'MATCHES ''/@''');
      END IF;
    
    END IF;

END TRG_CUSTOMER;